{
 "title": "UPS Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "kwhprice", "label": "kWh Price (₽)" }
  ]
 },
 "panels": [
  {
   "title": "Model Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pwrstat_ups_properties{instance=\"pwrstat-exporter:9101\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pwrstat_ups_state{instance=\"pwrstat-exporter:9101\", state=\"normal\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Battery capacity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pwrstat_ups_battery_cap_percentages{instance=\"pwrstat-exporter:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current load",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pwrstat_ups_load_percentages{instance=\"pwrstat-exporter:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last battery test passed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pwrstat_ups_last_battery_test_timestamp_seconds{instance=\"pwrstat-exporter:9101\", result=\"passed\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Today's usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(pwrstat_ups_load_watts{instance=\"pwrstat-exporter:9101\"}[1d]) / 1000 / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Firmware Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pwrstat_ups_properties{instance=\"pwrstat-exporter:9101\"}",
     "legendFormat": "{{firmware}}"
    }
   ]
  },
  {
   "title": "Today's cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(pwrstat_ups_load_watts{instance=\"pwrstat-exporter:9101\"}[1d]) / 1000 / 3600 * [[kwhprice]]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rating Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pwrstat_ups_properties{instance=\"pwrstat-exporter:9101\"}",
     "legendFormat": "{{rating_voltage}}"
    }
   ]
  },
  {
   "title": "Current power source",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pwrstat_ups_power_source{instance=\"pwrstat-exporter:9101\", source=\"utility power\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Average power usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(pwrstat_ups_load_watts{instance=\"pwrstat-exporter:9101\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last blackout",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pwrstat_ups_last_power_event_timestamp_seconds{instance=\"pwrstat-exporter:9101\", type=\"blackout\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "This week's usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(pwrstat_ups_load_watts{instance=\"pwrstat-exporter:9101\"}[7d]) / 1000 / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery remaining runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pwrstat_ups_battery_runtime_minutes{instance=\"pwrstat-exporter:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rating Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pwrstat_ups_properties{instance=\"pwrstat-exporter:9101\"}",
     "legendFormat": "{{rating_power}}"
    }
   ]
  },
  {
   "title": "This week's cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(pwrstat_ups_load_watts{instance=\"pwrstat-exporter:9101\"}[7d]) / 1000 / 3600 * [[kwhprice]]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "pwrstat_ups_utility_voltage_volts{instance=\"pwrstat-exporter:9101\"}",
     "legendFormat": "Input voltage"
    },
    {
     "expr": "pwrstat_ups_output_voltage_volts{instance=\"pwrstat-exporter:9101\"}",
     "legendFormat": "Output voltage"
    }
   ]
  },
  {
   "title": "This month's usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(pwrstat_ups_load_watts{instance=\"pwrstat-exporter:9101\"}[30d]) / 1000 / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "This month's cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(pwrstat_ups_load_watts{instance=\"pwrstat-exporter:9101\"}[30d]) / 1000 / 3600 * [[kwhprice]]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated yearly usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(pwrstat_ups_load_watts{instance=\"pwrstat-exporter:9101\"}[30d]) * 24 * 365 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "pwrstat_ups_load_watts{instance=\"pwrstat-exporter:9101\"}",
     "legendFormat": "Watts"
    }
   ]
  },
  {
   "title": "Estimated yearly cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(pwrstat_ups_load_watts{instance=\"pwrstat-exporter:9101\"}[30d]) * 24 * 365 / 1000 * [[kwhprice]]",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}